// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MiniRedmine.Web.DbModels;
using System;

namespace MiniRedmine.Web.Migrations
{
    [DbContext(typeof(RedmineUDB4Context))]
    [Migration("20180823151554_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiniRedmine.Web.DbModels.UserTemplate", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("UserId");

                    b.Property<int>("ActivityId");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.Property<double>("Hours");

                    b.HasKey("Id", "UserId");

                    b.ToTable("UserTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
