// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniRedmine.Web.DbModels;

namespace MiniRedmine.Web.Migrations
{
    [DbContext(typeof(RedmineUDB4Context))]
    partial class RedmineUDB4ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("MiniRedmine.Web.DbModels.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("IpAddress")
                        .IsRequired();

                    b.Property<DateTime?>("LastAccess");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MiniRedmine.Web.DbModels.UserTemplate", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("UserId");

                    b.Property<int>("ActivityId");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.Property<double>("Hours");

                    b.HasKey("Id", "UserId");

                    b.ToTable("UserTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
