name: .NET Core

on:
  push:
    branches: [ principal ]
  pull_request:
    branches: [ principal ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x]
    
    runs-on: ubuntu-latest   

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1      
      with:
        node-version: ${{ matrix.node-version }}   
        working-directory: ./FrontEnd         
    - run: npm install      
    - run: npm run publish --if-present
