name: .NET Core + Webpack

on:
  push:
    branches: [ principal ]
  pull_request:
    branches: [ principal ]

jobs:
  build-net:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
  build-front:
    strategy:
      matrix:
        node-version: [14.x]    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM packages        
        run: npm install
        working-directory: ./MiniRedmine.Web/FrontEnd
      - name: Publish frontend        
        run: npm run publish --if-present
        working-directory: ./MiniRedmine.Web/FrontEnd
#  publish-package:
#    runs-on: ubuntu-latest    
#    needs: [build-net,build-front]
#    steps:      
#      - name: Publish Artifact
#        run: dotnet publish --configuration Release --no-restore --output /Artifact
#        working-directory: ./MiniRedmine.Web
        
      
